### Development environment configuration
[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"

# The rpc-url and network-passphrase are required for all environments.
# Coming soon: If given `run-locally = true`, the `network` will be launched with:
# `stellar network container start local`

[[development.accounts]]
name = "me"
default = true

# You can provide an expanded definition for each account:
#   - `name`: the only required field, an identity with this name will be created
#      with `stellar keys`.
#   - `default`: whether to use this account as the `--source` for commands
#     that need one. Only one default is allowed. The keypair will be generated
#      and saved in the `.soroban/identity` directory.
# Coming Soon: # If you provide just a string, an identity with this name will be created with
# `soroban keys`, which saves the mnemonic in `.soroban/identity`. E.g.: "alice"

[development.contracts]
example_core = { client = true }
example_status_message = { client = true }

# List each contract individually.
# `workspace = true` indicates that this project is part of the local cargo workspace.
# In dev & test environments, workspace contracts will be automatically built, deployed, initialized, bound, and imported.
# Coming Soon: Auto-build, -deploy, -bind, and -import all contracts in Cargo workspace
# Only supported in development & test environments
# cargo-workspace = true

# Coming Soon: Initialization steps for the contract, to be run after deployment.
# Only supported in `development` and `test` environments.
# You only need to specify the slop (everything after the `--`) for calls to
# `soroban contract invoke` for the given contract. Uses `default-account`
# by default; to use another, prefix with `SOROBAN_ACCOUNT=other-account`.
# init = """
# initialize --symbol ABND --decimal 7 --name abundance --admin me
# mint --amount 2000000 --to me"
# """

# Coming Soon: Specify live contracts to bind & import in this project using the given name.
# During initialization, these contracts will also be "spooned" into the development network,
# meaning that their data will match the live network at the given sequence number.
# [development.contracts.eurc]
# environment = "production"
# address = "C..."
# at-ledger-sequence = 50153603

### Staging environment configuration
[staging.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[[staging.accounts]]
name = "testnet-user"
default = true

[staging.contracts]
# soroban-atomic-swap-contract = "C123..."
# soroban-auth-contract = "C234..."
# soroban-errors-contract = "C345..."
# soroban-hello-world-contract = "C456..."
# soroban-increment-contract = "C567..."
# soroban-token-contract = "C678..."
# eurc = "C789..."

### Production environment configuration
[production.network]
rpc-url = "https://our-custom-rpc-provider.cool"
network-passphrase = "Public Global Stellar Network ; September 2015"

[[production.accounts]]
name = "official-team-account"
default = true

[production.contracts]
# soroban-atomic-swap-contract = "C987..."
# soroban-auth-contract = "C876..."
# soroban-errors-contract = "C765..."
# soroban-hello-world-contract = "C654..."
# soroban-increment-contract = "C543..."
# soroban-token-contract = "C432..."
# eurc = "C321..."
